### ISSUE TITLE
Fix sorting of version numbers

### ISSUE THREAD

**Issue by lsilvapvt** [pivotalservices/artifactory-resource#1]
Sorting is currently done in a jq statement using the version number as a string, which causes sorting problems with more complex version number structures (e.g.  (e.g. 1.0.rc.9 is listed as newer version than 1.0.rc.10) .

**Comment by Rukenshia** [comment]
would be awesome to have this fixed.

**Comment by trayo** [comment]
@lsilvapvt hit the nail on the head about the numbers being strings causing the sort to cause a problem. For anyone unfamiliar it will sort the numbers `1, 2, 10, 20, 100, 200` as `1, 10, 100, 2, 20, 200`.

I was looking at this because it was causing us headaches at work and came up with this jq filter:

`[.children[].uri | . as $uri | capture($regex).version as $version | { uri: $uri, version: $version | tonumber }] | sort_by(.version) | last`

In, short it takes the number using the regex, converts it to an integer and sorts it. To get the numerically last value it simply needs `| last` at the end like:

`[.children[].uri | capture($regex).version as $version | {version: $version | tonumber }] | sort_by(.version) | last`

I also added in the `uri` to the object to demonstrate that the full uri could still be grabbed in order to curl the full url.

The only caveat with this method is that the regex provided has to be pointed at a specific section of the uri that contains only a number. Because it converts the `version` regex group to a number it wouldn't work with trying to capture all of `1.0.rc.9` and comparing it to `1.0.rc.10`. Instead the regex with the capture group would have to be like `.*rc\.(?<version>.*)`

I think some sort of advanced regex could be implemented to support versioning with `rc` or other characters, but it would probably have to use more capture groups. An example of the regex would be like: `(?<major>.*)\.(?<minor>.*)\.(?<patch>.*)\.rc\.(?<release>.*).

I'd be happy to work on a pull request with this feature, but would need some direction on which solution would be more acceptable.

**Comment by gchenuet** [comment]
Hi,

Any update about this bug/enhancement ?

Thanks

**Comment by Rukenshia** [comment]
@trayo I think it would make sense to use something like [node-semver](https://github.com/npm/node-semver) to sort the versions correctly, but then this custom resource should have a flag to turn semver off.

**Comment by geofffranks** [comment]
It seems like this was addressed in https://github.com/pivotalservices/artifactory-resource/commit/70d76041f6e30c748aae0043fa591517169dd14f, but this isn't handling versions of format `x.y.z-patch1`, or anything where the last component (when split on `.`) is not entirely numeric. Is this something that can be supported?

e.g. `3.1.0-2ubuntu0.4`, `3.1.0-2`,  `3.1.0-ubuntu-0.4`

**Comment by vorbidan** [comment]
Also, for messed-up artifactory repos (like mine), where it is allowed to publish the artifact with the exactly the same version, it would be nice to maintain versioning by "modified" field, which is available through AQL. 
In general maybe it is better to do "check" and "in" via Artifactory Search API and AQL vs. the Storage API.

**Comment by ksinkar** [comment]
This bug is not yet resolved. The sorting still follows the rules originally defined in the bug report. 
When you do a manual deploy then, an older version of the artifact (0.3.9) gets picked up instead of the latest version (0.3.37)
![Screenshot_2019-10-24 artifact - Concourse(1)](https://user-images.githubusercontent.com/649059/67470130-91c48180-f64d-11e9-825c-4cbdaaf1153f.png)

**Comment by sjwl** [comment]
@ksinkar if you're pulling from Docker Hub (hub.docker.com/pivotalservices/artifactory-resource), you will run into this issue.  Try building your own Docker image off `master` branch, and try again.

I had the same problem until I realized the fix for this (#26) was merged _after_ version `0.1` which is what you'll find on Docker Hub.
